// web3
export const WEB3_INITIALIZED = "WEB3_INITIALIZED";

// session
export const SESSION_DATA_FETCHED = "SESSION_DATA_FETCHED";

// wallet
export const GET_WALLET_INFO_SUCCESS = "GET_WALLET_INFO_SUCCESS";

// transactions
export const TRANSACTION_STATUS_UPDATED = "TRANSACTION_STATUS_UPDATED";
